project:
  type: book

book:
  title: "La météo des élections"
  
  author: 
    - name: "Carole Doucerain"
    - name: "Léo Streith"
    - name: "Alycia Frochot"
    - name: "Etienne Henry"
      
  date: today
  description:  |
    TO WRITE
  
  sidebar: 
    style: "docked"
    collapse-level: 1

  page-footer: 
    center: "Code source available on [{{< fa brands github >}}](https://github.com/cdoucerain/meteo_des_elections.git)"
    border: true
  
  reader-mode: false
  search: false
  
  chapters:
    - index.qmd
    - chapters/chapter_1__agregate_wheather_vote.qmd
    - chapters/chapter_2__abstention_rain.qmd
    
format:
  html:
    theme: [cosmo, css/styles.scss]
    code-copy: true
    code-line-numbers: false
